defaults: &defaults
help_page_url: "http://www.railstutorial.org/help"
book_url: "http://www.railstutorial.org/book"
google_logo_url: "https://img.icons8.com/color/48/000000/google-logo.png"
lucide_js_path: "https://cdn.jsdelivr.net/npm/lucide@latest/dist/umd/lucide.js"
edit_url: "http://gravatar.com/emails"

page_6: 6
page_20: 20

user:
  max_name_length: 50
  max_email_length: 255
  hundred_years: 100

word:
  pagy_items: 10
  filter_days:
    last_7_days: 7
    last_30_days: 30
  date_format: "%d/%m/%Y"

course:
  min_duration: 1
  max_duration: 365
  date_format: "%d/%m/%Y"
  page_number: 10

question:
  answer_defaults_number: 4
  question_types:
    single_choice: "single_choice"
    multiple_choice: "multiple_choice"

test_pass_percentage: 80.0

max_percentage: 100
test:
  page_number: 10

user_courses:
  timestamp_format: "%d/%m/%Y %H:%M"
  date_format: "%d/%m/%Y"
  test_pass_mark: 80

commit:
  save_draft: "save_draft"
  true_value: "true"

test_expired_threshold: 1 # minutes
lesson:
  date_format: "%d/%m/%Y"
  pagy_items: 10

component_types:
  word: "word"
  test: "test"
  paragraph: "paragraph"

filter_days:
  last_7_days: "last_7_days"
  last_30_days: "last_30_days"
  today: "today"

actions:
  create: "create"
  update: "update"
  destroy: "destroy"

default_mail_from: "noreply@sjp-elearning.com"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
